//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class incompleteDataWsdlExceptionType : operationFailedWsdlExceptionType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noAuthorizationWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(incompleteDataWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validationWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(incompleteOperationWsdlExceptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class operationFailedWsdlExceptionType : gfiWsdlExceptionType {
        
        private object erroneoField;
        
        private object completoField;
        
        private errorDetailType[] errorDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public object erroneo {
            get {
                return this.erroneoField;
            }
            set {
                this.erroneoField = value;
                this.RaisePropertyChanged("erroneo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object completo {
            get {
                return this.completoField;
            }
            set {
                this.completoField = value;
                this.RaisePropertyChanged("completo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errorDetails", Order=2)]
        public errorDetailType[] errorDetails {
            get {
                return this.errorDetailsField;
            }
            set {
                this.errorDetailsField = value;
                this.RaisePropertyChanged("errorDetails");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class errorDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errIdField;
        
        private string errMsgField;
        
        private string errDetailField;
        
        private errorDetailType[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errId {
            get {
                return this.errIdField;
            }
            set {
                this.errIdField = value;
                this.RaisePropertyChanged("errId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errDetail {
            get {
                return this.errDetailField;
            }
            set {
                this.errDetailField = value;
                this.RaisePropertyChanged("errDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("details", Order=3)]
        public errorDetailType[] details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noDataFoundWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(duplicatedDataWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operationFailedWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(noAuthorizationWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(incompleteDataWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(validationWsdlExceptionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(incompleteOperationWsdlExceptionType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public abstract partial class gfiWsdlExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusField;
        
        private string[] descriptionField;
        
        private string stacktraceField;
        
        private string classNameField;
        
        private string messageField;
        
        private object infoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("description", Order=1)]
        public string[] description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string stacktrace {
            get {
                return this.stacktraceField;
            }
            set {
                this.stacktraceField = value;
                this.RaisePropertyChanged("stacktrace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string className {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
                this.RaisePropertyChanged("className");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object info {
            get {
                return this.infoField;
            }
            set {
                this.infoField = value;
                this.RaisePropertyChanged("info");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class noDataFoundWsdlExceptionType : gfiWsdlExceptionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class duplicatedDataWsdlExceptionType : gfiWsdlExceptionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas")]
    public partial class ConsultaFechaEmpresaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idEmpresaField;
        
        private string cveDiaLiquidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idEmpresa {
            get {
                return this.idEmpresaField;
            }
            set {
                this.idEmpresaField = value;
                this.RaisePropertyChanged("idEmpresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cveDiaLiquida {
            get {
                return this.cveDiaLiquidaField;
            }
            set {
                this.cveDiaLiquidaField = value;
                this.RaisePropertyChanged("cveDiaLiquida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class noAuthorizationWsdlExceptionType : operationFailedWsdlExceptionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class validationWsdlExceptionType : operationFailedWsdlExceptionType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
    public partial class incompleteOperationWsdlExceptionType : operationFailedWsdlExceptionType {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/definitions", ConfigurationName="ServiceReference1.FechasPortType")]
    public interface FechasPortType {
        
        // CODEGEN: Generating message contract since the operation consultarFechaEmpresa is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="consultaFechaEmpresa", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.incompleteDataWsdlExceptionType), Action="consultaFechaEmpresa", Name="incompleteDataWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.operationFailedWsdlExceptionType), Action="consultaFechaEmpresa", Name="operationFailedWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(gfiWsdlExceptionType))]
        Client.ServiceReference1.consultarFechaEmpresaResponse consultarFechaEmpresa(Client.ServiceReference1.consultarFechaEmpresaRequest request);
        
        // CODEGEN: Generating message contract since the operation consultarFechaHoraBD is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="consultaFechaHoraBD", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.operationFailedWsdlExceptionType), Action="consultaFechaHoraBD", Name="operationFailedWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(gfiWsdlExceptionType))]
        Client.ServiceReference1.consultarFechaHoraBDResponse consultarFechaHoraBD(Client.ServiceReference1.consultarFechaHoraBDRequest request);
        
        // CODEGEN: Generating message contract since the operation obtenerFormatoFecha is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="formatoFecha", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.validationWsdlExceptionType), Action="formatoFecha", Name="validationWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.operationFailedWsdlExceptionType), Action="formatoFecha", Name="operationFailedWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(gfiWsdlExceptionType))]
        Client.ServiceReference1.obtenerFormatoFechaResponse obtenerFormatoFecha(Client.ServiceReference1.obtenerFormatoFechaRequest request);
        
        // CODEGEN: Generating message contract since the operation obtenerFormatoFechaHM is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="formatoFechaHM", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.validationWsdlExceptionType), Action="formatoFechaHM", Name="validationWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.FaultContractAttribute(typeof(Client.ServiceReference1.operationFailedWsdlExceptionType), Action="formatoFechaHM", Name="operationFailedWsdlExceptionInfo", Namespace="http://interacciones.com/corp/exception/v2_0/schemas")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(gfiWsdlExceptionType))]
        Client.ServiceReference1.obtenerFormatoFechaHMResponse obtenerFormatoFechaHM(Client.ServiceReference1.obtenerFormatoFechaHMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFechaEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        public Client.ServiceReference1.ConsultaFechaEmpresaType consultaFechaEmpresaRequest;
        
        public consultarFechaEmpresaRequest() {
        }
        
        public consultarFechaEmpresaRequest(Client.ServiceReference1.ConsultaFechaEmpresaType consultaFechaEmpresaRequest) {
            this.consultaFechaEmpresaRequest = consultaFechaEmpresaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFechaEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime consultaFechaEmpresaResponse;
        
        public consultarFechaEmpresaResponse() {
        }
        
        public consultarFechaEmpresaResponse(System.DateTime consultaFechaEmpresaResponse) {
            this.consultaFechaEmpresaResponse = consultaFechaEmpresaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFechaHoraBDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        public string consultaFechaHoraBDRequest;
        
        public consultarFechaHoraBDRequest() {
        }
        
        public consultarFechaHoraBDRequest(string consultaFechaHoraBDRequest) {
            this.consultaFechaHoraBDRequest = consultaFechaHoraBDRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarFechaHoraBDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        public System.DateTime consultaFechaHoraBDResponse;
        
        public consultarFechaHoraBDResponse() {
        }
        
        public consultarFechaHoraBDResponse(System.DateTime consultaFechaHoraBDResponse) {
            this.consultaFechaHoraBDResponse = consultaFechaHoraBDResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFormatoFechaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime formatoFechaRequest;
        
        public obtenerFormatoFechaRequest() {
        }
        
        public obtenerFormatoFechaRequest(System.DateTime formatoFechaRequest) {
            this.formatoFechaRequest = formatoFechaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFormatoFechaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        public string formatoFechaResponse;
        
        public obtenerFormatoFechaResponse() {
        }
        
        public obtenerFormatoFechaResponse(string formatoFechaResponse) {
            this.formatoFechaResponse = formatoFechaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFormatoFechaHMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime formatoFechaHMRequest;
        
        public obtenerFormatoFechaHMRequest() {
        }
        
        public obtenerFormatoFechaHMRequest(System.DateTime formatoFechaHMRequest) {
            this.formatoFechaHMRequest = formatoFechaHMRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerFormatoFechaHMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://interacciones.com/corp/fechas/v1_0/schemas", Order=0)]
        public string formatoFechaHMResponse;
        
        public obtenerFormatoFechaHMResponse() {
        }
        
        public obtenerFormatoFechaHMResponse(string formatoFechaHMResponse) {
            this.formatoFechaHMResponse = formatoFechaHMResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FechasPortTypeChannel : Client.ServiceReference1.FechasPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FechasPortTypeClient : System.ServiceModel.ClientBase<Client.ServiceReference1.FechasPortType>, Client.ServiceReference1.FechasPortType {
        
        public FechasPortTypeClient() {
        }
        
        public FechasPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FechasPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FechasPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FechasPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.consultarFechaEmpresaResponse Client.ServiceReference1.FechasPortType.consultarFechaEmpresa(Client.ServiceReference1.consultarFechaEmpresaRequest request) {
            return base.Channel.consultarFechaEmpresa(request);
        }
        
        public System.DateTime consultarFechaEmpresa(Client.ServiceReference1.ConsultaFechaEmpresaType consultaFechaEmpresaRequest) {
            Client.ServiceReference1.consultarFechaEmpresaRequest inValue = new Client.ServiceReference1.consultarFechaEmpresaRequest();
            inValue.consultaFechaEmpresaRequest = consultaFechaEmpresaRequest;
            Client.ServiceReference1.consultarFechaEmpresaResponse retVal = ((Client.ServiceReference1.FechasPortType)(this)).consultarFechaEmpresa(inValue);
            return retVal.consultaFechaEmpresaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.consultarFechaHoraBDResponse Client.ServiceReference1.FechasPortType.consultarFechaHoraBD(Client.ServiceReference1.consultarFechaHoraBDRequest request) {
            return base.Channel.consultarFechaHoraBD(request);
        }
        
        public System.DateTime consultarFechaHoraBD(string consultaFechaHoraBDRequest) {
            Client.ServiceReference1.consultarFechaHoraBDRequest inValue = new Client.ServiceReference1.consultarFechaHoraBDRequest();
            inValue.consultaFechaHoraBDRequest = consultaFechaHoraBDRequest;
            Client.ServiceReference1.consultarFechaHoraBDResponse retVal = ((Client.ServiceReference1.FechasPortType)(this)).consultarFechaHoraBD(inValue);
            return retVal.consultaFechaHoraBDResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.obtenerFormatoFechaResponse Client.ServiceReference1.FechasPortType.obtenerFormatoFecha(Client.ServiceReference1.obtenerFormatoFechaRequest request) {
            return base.Channel.obtenerFormatoFecha(request);
        }
        
        public string obtenerFormatoFecha(System.DateTime formatoFechaRequest) {
            Client.ServiceReference1.obtenerFormatoFechaRequest inValue = new Client.ServiceReference1.obtenerFormatoFechaRequest();
            inValue.formatoFechaRequest = formatoFechaRequest;
            Client.ServiceReference1.obtenerFormatoFechaResponse retVal = ((Client.ServiceReference1.FechasPortType)(this)).obtenerFormatoFecha(inValue);
            return retVal.formatoFechaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.obtenerFormatoFechaHMResponse Client.ServiceReference1.FechasPortType.obtenerFormatoFechaHM(Client.ServiceReference1.obtenerFormatoFechaHMRequest request) {
            return base.Channel.obtenerFormatoFechaHM(request);
        }
        
        public string obtenerFormatoFechaHM(System.DateTime formatoFechaHMRequest) {
            Client.ServiceReference1.obtenerFormatoFechaHMRequest inValue = new Client.ServiceReference1.obtenerFormatoFechaHMRequest();
            inValue.formatoFechaHMRequest = formatoFechaHMRequest;
            Client.ServiceReference1.obtenerFormatoFechaHMResponse retVal = ((Client.ServiceReference1.FechasPortType)(this)).obtenerFormatoFechaHM(inValue);
            return retVal.formatoFechaHMResponse;
        }
    }
}
